plugin: amazon.aws.aws_ec2

regions:
  - us-east-2

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.Name        
    prefix: ""            

hostnames:
  - ip-address      

compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: /home/ubuntu/DevOps-Platform-Capstone/terraform/keys/devops-capstone-key.pem
